"use client";

import { useState, useCallback } from "react";
import { GenerationSettings, GeneratedImage, GenerationHistory } from "@/lib/types";
import { generateImages } from "@/lib/imagen-client";
import { generateId } from "@/lib/utils";

const HISTORY_KEY = "imagen_history";

function loadHistory(): GenerationHistory[] {
  try {
    return JSON.parse(localStorage.getItem(HISTORY_KEY) || "[]");
  } catch {
    return [];
  }
}

function saveHistory(history: GenerationHistory[]) {
  try {
    localStorage.setItem(HISTORY_KEY, JSON.stringify(history.slice(0, 50)));
  } catch {
    // If storage is full, clear and try again
    localStorage.removeItem(HISTORY_KEY);
  }
}

export function useGeneration() {
  const [images, setImages] = useState<GeneratedImage[]>([]);
  const [loading, setLoading] = useState(false);
  const [progress, setProgress] = useState({ done: 0, total: 0 });
  const [error, setError] = useState<string | null>(null);
  const [history, setHistory] = useState<GenerationHistory[]>([]);
  const [historyLoaded, setHistoryLoaded] = useState(false);

  const loadHistoryFromStorage = useCallback(() => {
    if (!historyLoaded) {
      setHistory(loadHistory());
      setHistoryLoaded(true);
    }
  }, [historyLoaded]);

  const generate = useCallback(async (settings: GenerationSettings) => {
    setLoading(true);
    setError(null);
    setProgress({ done: 0, total: settings.numberOfImages });
    setImages([]);

    try {
      const generated = await generateImages(settings, (done, total) => {
        setProgress({ done, total });
      });

      setImages(generated);

      // Save only metadata to history (no image data — too large for localStorage)
      const historyEntry: GenerationHistory = {
        id: generateId(),
        prompt: settings.prompt,
        timestamp: Date.now(),
        settings,
        imageCount: generated.length,
      };

      const prev = loadHistory();
      const updated = [historyEntry, ...prev];
      saveHistory(updated);
      setHistory(updated);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Unknown error");
    } finally {
      setLoading(false);
      setProgress({ done: 0, total: 0 });
    }
  }, []);

  const regenerateSingle = useCallback(
    async (image: GeneratedImage) => {
      setLoading(true);
      setError(null);

      try {
        const generated = await generateImages({ ...image.settings, numberOfImages: 1 });
        const newImage = generated[0];

        setImages((prev) => {
          const idx = prev.findIndex((img) => img.id === image.id);
          if (idx === -1) return prev;
          const next = [...prev];
          next[idx] = newImage;
          return next;
        });
      } catch (e) {
        setError(e instanceof Error ? e.message : "Unknown error");
      } finally {
        setLoading(false);
      }
    },
    []
  );

  const toggleFavorite = useCallback((id: string) => {
    setImages((prev) =>
      prev.map((img) => (img.id === id ? { ...img, favorite: !img.favorite } : img))
    );
  }, []);

  // Load history entry restores settings only; images are regenerated by user
  const loadFromHistory = useCallback((entry: GenerationHistory) => {
    return entry.settings;
  }, []);

  const clearHistory = useCallback(() => {
    localStorage.removeItem(HISTORY_KEY);
    setHistory([]);
  }, []);

  return {
    images,
    loading,
    progress,
    error,
    history,
    generate,
    regenerateSingle,
    toggleFavorite,
    loadFromHistory,
    clearHistory,
    loadHistoryFromStorage,
  };
}
